//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador.empleadoDA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicio/", ConfigurationName="empleadoDA.empleadoWS")]
    public interface empleadoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicio/empleadoWS/listarEmpleadosRequest", ReplyAction="http://servicio/empleadoWS/listarEmpleadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Controlador.empleadoDA.listarEmpleadosResponse listarEmpleados(Controlador.empleadoDA.listarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicio/empleadoWS/listarEmpleadosRequest", ReplyAction="http://servicio/empleadoWS/listarEmpleadosResponse")]
        System.Threading.Tasks.Task<Controlador.empleadoDA.listarEmpleadosResponse> listarEmpleadosAsync(Controlador.empleadoDA.listarEmpleadosRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicio/")]
    public partial class empleado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private int edadField;
        
        private int idField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleados", WrapperNamespace="http://servicio/", IsWrapped=true)]
    public partial class listarEmpleadosRequest {
        
        public listarEmpleadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleadosResponse", WrapperNamespace="http://servicio/", IsWrapped=true)]
    public partial class listarEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Controlador.empleadoDA.empleado[] @return;
        
        public listarEmpleadosResponse() {
        }
        
        public listarEmpleadosResponse(Controlador.empleadoDA.empleado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface empleadoWSChannel : Controlador.empleadoDA.empleadoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class empleadoWSClient : System.ServiceModel.ClientBase<Controlador.empleadoDA.empleadoWS>, Controlador.empleadoDA.empleadoWS {
        
        public empleadoWSClient() {
        }
        
        public empleadoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public empleadoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public empleadoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public empleadoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.empleadoDA.listarEmpleadosResponse Controlador.empleadoDA.empleadoWS.listarEmpleados(Controlador.empleadoDA.listarEmpleadosRequest request) {
            return base.Channel.listarEmpleados(request);
        }
        
        public Controlador.empleadoDA.empleado[] listarEmpleados() {
            Controlador.empleadoDA.listarEmpleadosRequest inValue = new Controlador.empleadoDA.listarEmpleadosRequest();
            Controlador.empleadoDA.listarEmpleadosResponse retVal = ((Controlador.empleadoDA.empleadoWS)(this)).listarEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.empleadoDA.listarEmpleadosResponse> Controlador.empleadoDA.empleadoWS.listarEmpleadosAsync(Controlador.empleadoDA.listarEmpleadosRequest request) {
            return base.Channel.listarEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.empleadoDA.listarEmpleadosResponse> listarEmpleadosAsync() {
            Controlador.empleadoDA.listarEmpleadosRequest inValue = new Controlador.empleadoDA.listarEmpleadosRequest();
            return ((Controlador.empleadoDA.empleadoWS)(this)).listarEmpleadosAsync(inValue);
        }
    }
}
